theme: jekyll-theme-hacker
title: Calculator Hacks
description: Simple Hack programs for your Casio Colograph calculator!
show_downloads: true
github:
  zip_url: https://github.com/calculatorhacks/formula/archive/main.zip
  tar_url: https://github.com/calculatorhacks/formula/archive/main.zip
  another_url: https://github.com/calculatorhacks/formula/archive/main.zip
